#!/bin/bash
export LC_ALL=C
export LANG=en_US.UTF-8
if [ -n "$BUILD_INITIALIZE" ]; then
  rm opencv/.git/index.lock 2>/dev/null
  rm opencv_extra/.git/index.lock 2>/dev/null
  rm opencv_contrib/.git/index.lock 2>/dev/null
  rm opencv_extra/.git/refs/heads/master.lock 2>/dev/null
  exit 0
fi

exec $@
