set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR powerpc64le)

set(CMAKE_C_COMPILER /usr/bin/powerpc64le-linux-gnu-gcc-7)
set(CMAKE_CXX_COMPILER /usr/bin/powerpc64le-linux-gnu-g++-7)

set(CMAKE_FIND_ROOT_PATH /usr/powerpc64le-linux-gnu)

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
